version: "3.3"
services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./inputs:/opt/bitnami/spark/inputs
      - ./outputs:/opt/bitnami/spark/outputs
      - ./requirements.txt:/requirements.txt
      - ./udf:/opt/bitnami/spark/udf
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker: &worker
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./inputs:/opt/bitnami/spark/inputs
      - ./outputs:/opt/bitnami/spark/outputs
      - ./requirements.txt:/requirements.txt
      - ./udf:/opt/bitnami/spark/udf
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: WORKER
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-worker-2:
    <<: *worker

  spark-worker-3:
    <<: *worker

  spark-worker-4:
    <<: *worker



